### ISSUE TITLE
Login system doesn't work

### ISSUE THREAD

**Issue by ghost** [themaxsandelin/twitter#3]
When you try to login to your account even if the password is correct, you can't login.
I have messages like: "Guess what? Invalid login, b*tch." or  "Game over. Try again."

**Comment by themaxsandelin** [comment]
Did you go through the proper setup? With a MySQL database?

**Comment by ghost** [comment]
When I upload the sql file, I got this error: #1064 - Syntax error in SQL query near 'NULL DEFAULT NOW()
) ENGINE=Innodb DEFAULT CHARSET=utf8' line 15

**Comment by ghost** [comment]
I've made all the changes inside the database.php file with my DB credentials

**Comment by themaxsandelin** [comment]
Probably SQL versioning issue. Try googling around a bit to see if you can figure it out. I might have time to look at this later this week, but I'm very occupied with work and this project isn't really shared to be "used".
